MODEL:
  MODEL_NAME: "GCN"
  DIM_H: 64

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.001
  WEIGHT_DECAY_BIAS: 0.0001
  BIAS_LR_FACTOR: 2

  BATCH_SIZE: 96
  EPOCHS: 40

  WARMUP_METHOD: 'StepLR'
  STEPS: 8
  LOSS: 'MAE'

DATASET:
  GRAPH_FEATURE: True