MODEL:
  MODEL_NAME: 'MLP'
  # HIDDEN_LAYERS: [400,256,64,32]
  HIDDEN_LAYERS: [400,100]
  
SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.001
  WEIGHT_DECAY_BIAS: 0.0001
  BIAS_LR_FACTOR: 2

  BATCH_SIZE: 128
  EPOCHS: 250

  WARMUP_METHOD: 'StepLR'
  STEPS: 80