MODEL:
  MODEL_NAME: 'MLP'
  HIDDEN_LAYERS: [400,256,64,32]
  
SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.001
  WEIGHT_DECAY_BIAS: 0.0001
  BIAS_LR_FACTOR: 2

  BATCH_SIZE: 64
  EPOCHS: 1000

  WARMUP_METHOD: 'StepLR'
  STEPS: 150


#0.0813360